name: Compose Docker tag list (semver + optional latest)
description: 'Compose tags for a given API version (exact semver), optionally including latest'
inputs:
  image-name:
    description: 'Base image name (e.g., ghcr.io/owner/repo)'
    required: true
  ver:
    description: 'API version (patch)'
    required: true
  max-version:
    description: 'Highest version across the matrix (exact semver)'
    required: true
  include-latest:
    description: 'Include latest alias when ver == max-version'
    required: false
    default: 'true'
outputs:
  list:
    description: 'Newline-delimited tag list'
    value: ${{ steps.t.outputs.list }}
runs:
  using: composite
  steps:
    - name: Build tags
      id: t
      shell: bash
      run: |
        set -euo pipefail
        V='${{ inputs.ver }}'
        LIST="${{ inputs['image-name'] }}:${V}"
        if [ "${{ inputs['include-latest'] }}" = "true" ] && [ "$V" = "${{ inputs['max-version'] }}" ]; then
          LIST="${LIST}"$'\n'"${{ inputs['image-name'] }}:latest"
        fi
        {
          echo 'list<<__TAGS__'
          printf '%s\n' "$LIST"
          echo '__TAGS__'
        } >> "$GITHUB_OUTPUT"
