name: CI
on: [push, pull_request]
jobs:
  ci:
    uses: <org>/actual-auto-ci/.github/workflows/ci.yml@v1
    with:
      node-version: '20'
      package-manager: npm
      lint: true
      format-check: true
      test: true

