name: Compute Actual API versions (top 3 stable)
description: 'Determine the latest three stable @actual-app/api versions (exact semver)'
inputs: {}
outputs:
  matrix:
    description: 'JSON array of three versions (exact semver)'
    value: ${{ steps.v.outputs.matrix }}
  max_version:
    description: 'Highest semver in the selection'
    value: ${{ steps.v.outputs.max_version }}
runs:
  using: composite
  steps:
    - name: Compute versions
      id: v
      shell: bash
      run: |
        set -euo pipefail
        ALL=$(npm view @actual-app/api versions --json)
        JSON=$(echo "$ALL" | jq -c '
          # Parse all stable semvers and sort ascending
          [ .[]
            | select(type=="string" and test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))
            | { v: ., p: (split(".")|map(tonumber)) } ]
          | sort_by(.p)
          | { list: (.[-3:] // [] | map(.v)), max_version: (.[-1].v // "") }
        ')
        echo "matrix=$(echo "$JSON" | jq -c .list)" >> $GITHUB_OUTPUT
        echo "max_version=$(echo "$JSON" | jq -r .max_version)" >> $GITHUB_OUTPUT
