name: Compute Actual API versions
description: 'Determine latest patch for the last N stable @actual-app/api majors'
inputs:
  majors-window:
    description: 'Number of latest majors to include'
    required: true
outputs:
  matrix:
    description: 'JSON array of versions (latest patch per major)'
    value: ${{ steps.v.outputs.matrix }}
  max_major:
    description: 'Highest major in the selection'
    value: ${{ steps.v.outputs.max_major }}
runs:
  using: composite
  steps:
    - name: Compute versions
      id: v
      shell: bash
      run: |
        set -euo pipefail
        ALL=$(npm view @actual-app/api versions --json)
        JSON=$(echo "$ALL" | jq -c --argjson n "${{ inputs.majors-window }}" '
          # Build parsed list with numeric parts and major
          [ .[]
            | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))
            | { v: ., p: (split(".")|map(tonumber)), major: ((split(".")|.[0]|tonumber)) } ] as $parsed
          # Determine latest N majors (by value, descending)
          | ($parsed | map(.major) | unique | sort | reverse | .[:$n]) as $majors
          # Keep only entries from selected majors
          | ($parsed | map(select(.major as $m | $majors | index($m)))) as $sel
          # For each major, pick the latest patch (by p), then sort ascending by p and emit versions
          | { matrix: ($sel | sort_by(.major, .p) | group_by(.major) | map(.[-1]) | sort_by(.p) | map(.v)),
              max_major: ($majors[0] // "") }
        ')
        echo "matrix=$(echo "$JSON" | jq -c .matrix)" >> $GITHUB_OUTPUT
        echo "max_major=$(echo "$JSON" | jq -r .max_major)" >> $GITHUB_OUTPUT
